package com.example.cityapp.model

import com.example.cityapp.R

object FakeCityDataSource {
    val cities = listOf(
        City(
            id = 1,
            name = "Jakarta",
            description = "Jakarta (/dʒəˈkɑːrtə/; pengucapan bahasa Indonesia: [dʒaˈkarta] ( simak)), secara resmi bernama Daerah Khusus Ibukota Jakarta atau DKI Jakarta) adalah ibu kota negara dan kota terbesar di Indonesia. Jakarta merupakan satu-satunya kota di Indonesia yang memiliki status setingkat provinsi. Jakarta terletak di pesisir bagian barat laut Pulau Jawa. Dahulu pernah dikenal dengan beberapa nama di antaranya Sunda Kelapa, Jayakarta, dan Batavia. Di dunia internasional Jakarta juga mempunyai julukan J-Town, atau lebih populer lagi The Big Durian karena dianggap kota yang sebanding New York City (Big Apple) di Indonesia.\n" +
                    "\n" +
                    "Jakarta memiliki luas sekitar 664,01 km² (lautan: 6.977,5 km²), dengan penduduk berjumlah 11.100.929 jiwa (2020). Wilayah metropolitan Jakarta (Jabodetabek) yang berpenduduk sekitar 28 juta jiwa, merupakan metropolitan terbesar di Asia Tenggara atau urutan kedua di dunia.\n" +
                    "\n" +
                    "Sebagai pusat bisnis, politik, dan kebudayaan, Jakarta merupakan tempat berdirinya kantor-kantor pusat BUMN, perusahaan swasta, dan perusahaan asing. Kota ini juga menjadi tempat kedudukan lembaga-lembaga pemerintahan dan kantor sekretariat ASEAN. Jakarta dilayani oleh dua bandar udara, yakni Bandara Soekarno–Hatta dan Bandara Halim Perdanakusuma, serta tiga pelabuhan laut di Tanjung Priok, Sunda Kelapa, dan Ancol. Nama Jakarta sudah digunakan sejak masa pendudukan Jepang tahun 1942, untuk menyebut wilayah bekas Gemeente Batavia yang diresmikan pemerintah Hindia Belanda pada tahun 1905. Nama \"Jakarta\" merupakan kependekan dari kata Jayakarta (aksara Dewanagari: जयकृत), yaitu nama dari Bahasa Sanskerta yang diberikan oleh orang-orang Demak dan Cirebon di bawah pimpinan Fatahillah (Faletehan) setelah menyerang dan berhasil menduduki pelabuhan Sunda Kelapa pada tanggal 22 Juni 1527 dari Portugis. Nama ini diterjemahkan sebagai \"kota kemenangan\" atau \"kota kejayaan\", namun sejatinya berarti \"kemenangan yang diraih oleh sebuah perbuatan atau usaha\" karena berasal dari dua kata Sanskerta yaitu Jaya (जय) yang berarti \"kemenangan\" dan Karta (कृत) yang berarti \"dicapai\".\n" +
                    "\n" +
                    "Bentuk lain ejaan nama kota ini telah sejak lama digunakan. Sejarawan Portugis, João de Barros, dalam Décadas da Ásia (1553) menyebutkan keberadaan \"Xacatara dengan nama lain Caravam (Karawang)\". Sebuah dokumen (piagam) dari Banten (k. 1600) yang dibaca ahli epigrafi Van der Tuuk juga telah menyebut istilah wong Jaketra, demikian pula nama Jaketra juga disebutkan dalam surat-surat Sultan Banten dan Sajarah Banten (pupuh 45 dan 47) sebagaimana diteliti Hoessein Djajadiningrat. Laporan Cornelis de Houtman tahun 1596 menyebut Pangeran Wijayakrama sebagai koning van Jacatra (raja Jakarta). Jakarta pertama kali dikenal sebagai salah satu pelabuhan Kerajaan Sunda yang bernama Sunda Kalapa (Aksara Sunda: ᮞᮥᮔ᮪ᮓ ᮊᮜᮕ), berlokasi di muara Sungai Ciliwung. Ibu kota Kerajaan Sunda yang dikenal sebagai Dayeuh Pakuan Padjadjaran atau Pajajaran (sekarang Bogor) dapat ditempuh dari pelabuhan Sunda Kalapa selama dua hari perjalanan. Menurut sumber Portugis, Sunda Kalapa merupakan salah satu pelabuhan yang dimiliki Kerajaan Sunda selain pelabuhan Banten, Pontang, Cigede, Tamgara dan Cimanuk. Sunda Kalapa yang dalam teks ini disebut Kalapa dianggap pelabuhan yang terpenting karena dapat ditempuh dari ibu kota kerajaan yang disebut dengan nama Dayo (dalam bahasa Sunda modern: dayeuh yang berarti \"ibu kota\") dalam tempo dua hari. Kerajaan Sunda sendiri merupakan kelanjutan dari Kerajaan Tarumanagara pada abad ke-5 sehingga pelabuhan ini diperkirakan telah ada sejak abad ke-5 dan diperkirakan merupakan ibu kota Tarumanagara yang disebut Sundapura (bahasa Sanskerta yang berarti \"Kota Sunda\").",
            photo = R.drawable.jakarta
        ),
        City(
            id = 2,
            name = "Makassar",
            description = "Kota Makassar adalah ibu kota provinsi Sulawesi Selatan. Makassar merupakan kota metropolitan terbesar di kawasan Indonesia Timur dan pada masa lalu pernah menjadi ibu kota Negara Indonesia Timur dan Provinsi Sulawesi. Makassar terletak di pesisir barat daya Pulau Sulawesi dan berbatasan dengan Selat Makassar di sebelah barat, Kabupaten Kepulauan Pangkajene di sebelah utara, Kabupaten Maros di sebelah timur dan Kabupaten Gowa di sebelah selatan. Nama Makassar sudah disebutkan dalam pupuh 14/3 kitab Nagarakretagama karya Mpu Prapanca pada abad ke-14, sebagai salah satu daerah taklukkan Majapahit. Walaupun demikian, Raja Gowa ke-9 Tumaparisi Kallonna (1510-1546) diperkirakan adalah tokoh pertama yang benar-benar mengembangkan kota Makassar. Ia memindahkan pusat kerajaan dari pedalaman ke tepi pantai, mendirikan benteng di muara Sungai Jeneberang, serta mengangkat seorang syahbandar untuk mengatur perdagangan.\n" +
                    "\n" +
                    "Pada abad ke-16, Makassar menjadi pusat perdagangan yang dominan di Indonesia Timur, sekaligus menjadi salah satu kota terbesar di Asia Tenggara. Raja-raja Makassar menerapkan kebijakan perdagangan bebas yang ketat, di mana seluruh pengunjung ke Makassar berhak melakukan perniagaan di sana dan menolak upaya VOC (Belanda) untuk memperoleh hak monopoli di kota tersebut.\n" +
                    "\n" +
                    "Selain itu, sikap yang toleran terhadap agama berarti bahwa meskipun Islam semakin menjadi agama yang utama di wilayah tersebut, pemeluk agama Kristen dan kepercayaan lainnya masih tetap dapat berdagang di Makassar. Hal ini menyebabkan Makassar menjadi pusat yang penting bagi orang-orang Melayu yang bekerja dalam perdagangan di Kepulauan Maluku dan juga menjadi markas yang penting bagi pedagang-pedagang dari Eropa dan Arab.Semua keistimewaan ini tidak terlepas dari kebijaksanaan Raja Gowa-Tallo yang memerintah saat itu (Sultan Alauddin, Raja Gowa, dan Sultan Awalul Islam, Raja Tallo).\n" +
                    "\n" +
                    "Kontrol penguasa Makassar semakin menurun seiring semakin kuatnya pengaruh Belanda di wilayah tersebut dan menguatnya politik monopoli perdagangan rempah-rempah yang diterapkan Belanda melalui VOC. Pada tahun 1669, Belanda, bersama dengan La Tenri Tatta Arung Palakka dan beberapa kerajaan sekutu Belanda Melakukan penyerangan terhadap kerajaan Islam Gowa-Tallo yang mereka anggap sebagai Batu Penghalang terbesar untuk menguasai rempah-rempah di Indonesia timur. Setelah berperang habis-habisan mempertahankan kerajaan melawan beberapa koalisi kerajaan yang dipimpin oleh belanda, akhirnya Gowa-Tallo (Makassar) terdesak dan dengan terpaksa menanda tangani Perjanjian Bongaya.\n" +
                    "\n" +
                    "Kota ini dahulu bernama Ujung Pandang dipakai pada tahun 1971 sampai tahun 1999. Alasan untuk mengganti nama Makassar menjadi Ujung Pandang dengan alasan politik, antara lain karena Makassar adalah nama sebuah suku bangsa padahal tidak semua penduduk kota Makassar adalah anggota dari etnik Makassar.\n" +
                    "\n" +
                    "Nama Kota Makassar diubah menjadi Ujung Pandang terjadi pada tanggal 31 Agustus 1971, berdasarkan Peraturan Pemerintah No. 51 tahun 1971.\n" +
                    "\n" +
                    "Saat itu, Kota Makassar dimekarkan dari 21 kilometer persegi menjadi 115,87 Kilometer persegi, terdiri dari 11 wilayah kecamatan dan 62 lingkungan dengan penduduk sekitar 700 ribu jiwa.\n" +
                    "\n" +
                    "Ujung Pandang sebenarnya adalah nama lain dari Makassar, yang dipakai sekitar tahun 1950-an sampai tahun 2000. Pergantian nama Makassar dengan Ujung Pandang ini dilatar belakangi oleh nama Makassar yang menjadi nama sebuah suku bangsa di Makassar.\n" +
                    "\n" +
                    "Nama Ujung Pandang sendiri adalah nama sebuah kampung di wilayah Kota Makassar. Ujung Pandang mulai dikenal pada masa pemerintahan Raja Gowa ke-X, Tunipalangga yang pada tahun 1545 mendirikan Benteng Ujung Pandang sebagai kelengkapan benteng-benteng kerajaan Gowa yang sudah ada sebelumnya.\n" +
                    "\n" +
                    "Terjadinya Perang Dunia Kedua dan berdirinya RI mengubah wajah Makassar. Perginya sebagian besar warga asing di tahun 1949 dan nasionalisasi perusahaan asing di akhir tahun 1950-an, membuatnya kembali menjadi sebuah kota provinsi.\n" +
                    "\n" +
                    "tepatnya 13 Oktober 1999, berdasarkan Peraturan Pemerintah Nomor 86 Tahun 1999 nama Ujung Pandang dikembalikan menjadi Kota Makassar. Aturan ini sesuai dengan Undang-Undang Pemerintahan Daerah luas wilayah bertambah kurang lebih 4 mil kearah laut 10.000 Ha, menjadi 27.577 Ha.\n" +
                    "\n" +
                    "Berawal dari proses reformasi yang terjadi sejak 21 Mei 1998, nama Makassar seolah kembali hidup untuk menggantikan Ujung Pandang. Barulah di penghujung masa jabatan Presiden BJ Habibie, nama Makassar kembali tanpa proses yang berbelit-belit.\n" +
                    "\n" +
                    "Dalam konsideran Peraturan Pemerintah No. 86 Tahun 1999, di antaranya menyebutkan bahwa perubahan itu wujud keinginan masyarakat Ujung Pandang dengan mendapat dukungan DPRD Ujung Pandang dan perubahan ini sejalan dengan pasal 5 ayat (3) Undang-Undang RI Nomor 22 tahun 1999, bahwa perubahan nama daerah, ditetapkan dengan Peraturan Pemerintah.\n" +
                    "\n" +
                    "Seiring perubahan dan pengembalian nama Makassar, maka nama Ujung Pandang kini tinggal kenangan dan selanjutnya semua elemen masyarakat kota mulai dari para budayawan, pemerintah serta masyarakat kemudian mengadakan penelurusan dan pengkajian sejarah Makassar, Hasilnya Pemerintah Daerah Nomor 1 Tahun 2000, menetapkan Hari jadi Kota Makassar, tanggal 9 November 1607. Dan untuk pertama kali Hari Jadi Kota Makassar ke 393, diperingati pada tanggal 9 November 2000. Nama Makassar berasal dari sebuah kata dalam bahasa Makassar \"Mangkasarak\" yang berarti yang metampakkan diri atau yang bersifat terbuka.",
            photo = R.drawable.makassasr
        ),
        City(
            id = 3,
            name = "Palu",
            description = "Kota Palu adalah Ibukota Provinsi Sulawesi Tengah, Indonesia. Palu merupakan kota yang terletak di Sulawesi Tengah, berbatasan dengan Kabupaten Donggala di sebelah barat dan Utara, Kabupaten Sigi di sebelah selatan, dan Kabupaten Parigi Moutong di sebelah timur. Kota Palu merupakan kota lima dimensi yang terdiri atas lembah, lautan, sungai, pegunungan, dan teluk. Koordinatnya adalah 0,35 – 1,20 LU dan 120 – 122,90 BT. Kota Palu dilewati oleh garis Khatulistiwa. Penduduk Kota Palu berjumlah 371.345 jiwa (2019). Asal usul nama kota Palu adalah kata Topalu'e yang artinya Tanah yang terangkat karena daerah ini awalnya lautan. Pernah terjadi gempa dan pergeseran lempeng (palu koro) sehingga daerah yang tadinya lautan tersebut terangkat dan membentuk daratan lembah yang sekarang menjadi Kota Palu.\n" +
                    "\n" +
                    "Istilah lain juga menyebutkan bahwa kata asal usul nama Kota Palu berasal dari bahasa Kaili VOLO yang berarti bambu yang tumbuh dari daerah Tawaeli sampai di daerah sigi. Bambu sangat erat kaitannya dengan masyarakat suku Kaili, ini dikarenakan ketergantungan masyarakat Kaili dalam penggunaan bambu sebagai kebutuhan sehari-hari mereka, baik itu dijadikan Bahan makanan (Rebung), Bahan bangunan (Dinding, tikar, dll), Perlengkapan sehari hari, permainan (Tilako), serta alat musik (Lalove).\n" +
                    "\n" +
                    "Kota Palu sekarang ini adalah bermula dari kerajaan yang terdiri dari kesatuan empat kampung, yaitu: Besusu, Tanggabanggo yang sekarang bernama Kelurahan Kamonji, Panggovia yang sekarang bernama Kelurahan Lere, dan Boyantongo yang sekarang bernama Kelurahan Baru. Mereka membentuk satu Dewan Adat disebut Patanggota. Salah satu tugasnya adalah memilih raja dan para pembantunya yang erat hubungannya dengan kegiatan kerajaan. Kerajaan Palu lama-kelamaan menjadi salah satu kerajaan yang dikenal dan sangat berpengaruh. Itulah sebabnya Belanda mengadakan pendekatan terhadap Kerajaan Palu. Belanda pertama kali berkunjung ke Palu pada masa kepemimpinan Raja Maili (Mangge Risa) untuk mendapatkan perlindungan dari Manado pada tahun 1868. Pada tahun 1888, Gubernur Belanda untuk Sulawesi bersama dengan bala tentara dan beberapa kapal tiba di Kerajaan Palu, mereka pun menyerang Kayumalue. Setelah peristiwa perang Kayumalue, Raja Maili terbunuh oleh pihak Belanda dan jenazahnya dibawa ke Palu. Setelah itu ia digantikan oleh Raja Jodjokodi, pada tanggal 1 Mei 1888, Raja Jodjokodi menandatangani perjanjian pendek kepada Pemerintah Hindia Belanda. Pada awal mulanya, Kota Palu merupakan pusat pemerintahan Kerajaan Palu. Pada masa penjajahan Belanda, Kerajaan Palu menjadi bagian dari wilayah kekuasaan (Onder Afdeling Palu) yang terdiri dari tiga wilayah yaitu Landschap Palu yang mencakup distrik Palu Timur, Palu Tengah, dan Palu Barat; Landschap Kulawi; dan Landschap Sigi Dolo.\n" +
                    "\n" +
                    "Pada tahun 1942, terjadi pengambilalihan kekuasaan dari Pemerintahan Belanda kepada pihak Jepang. Pada masa Perang Dunia II ini, kota Donggala yang kala itu merupakan ibu kota Afdeling Donggala dihancurkan oleh pasukan Sekutu maupun Jepang. Hal ini mengakibatkan pusat pemerintahan dipindahkan ke kota Palu pada tahun 1950. Saat itu, kota Palu berkedudukan sebagai Kepala Pemerintahan Negeri (KPN) setingkat wedana dan menjadi wilayah daerah Sulawesi Tengah yang berpusat di Kabupaten Poso sesuai Undang-Undang Nomor 4 Tahun 1950. Kota Palu kemudian mulai berkembang setelah dibentuknya Residen Koordinator Sulawesi Tengah Tahun 1957 yang menempatkan Kota Palu sebagai Ibu kota Keresidenan.\n" +
                    "\n" +
                    "Terbentuknya Provinsi Sulawesi Tengah berdasarkan Undang-Undang Nomor 13 Tahun 1964, status Kota Palu sebagai ibu kota ditingkatkan menjadi Ibu kota Provinsi Daerah Tingkat I Sulawesi Tengah. Kemudian pada tahun 1978, Kota Palu ditetapkan sebagai kota administratif berdasarkan Peraturan Pemerintah Nomor 18 Tahun 1978. Kini, berdasarkan Undang-Undang Nomor 4 Tahun 1994 Kota Palu ditingkatkan statusnya menjadi Kotamadya Palu. \n" +
                    "Kota Palu saat ini juga menjadi salah kawasan ekonomi khusus (KEK) di Indonesia bagian timur. Berbagai persiapan untuk ditetapkan Kota Palu sebagai kawasan ekonomi khusus telah dilakukan, penyiapan lahan seluas 1.520 hektare di Kecamatan Palu Utara, yang meliputi Kelurahan Pantoloan, Baiya, dan Lambara. Lahan seluas 1.520 hektare itu akan dibagi menjadi kawasan industri seluas 700 hektare, kawasan perumahan (500 hektare), kawasan pendidikan dan penelitian (100 hektare), kawasan komersial (100 hektare), daerah olahraga (50 hektare), kawasan pergudangan (50 hektare), kawasan perkebunan dan taman (20 hektare).",
            photo = R.drawable.palu
        ),
        City(
            id = 4,
            name = "Yogyakarta",
            description = "Kota Yogyakarta (bahasa Jawa: ꦏꦸꦛ\u200Bꦔꦪꦺꦴꦒꦾꦏꦂꦠ, translit. Kutha Ngayogyakarta, pengucapan bahasa Jawa: [kuʈɔ ŋajogjɔˈkart̪ɔ]) adalah ibu kota dan pusat pemerintahan Provinsi Daerah Istimewa Yogyakarta, Indonesia. Kota Yogyakarta adalah kediaman bagi Sultan Hamengkubuwana dan Adipati Paku Alam. Kota Yogyakarta merupakan salah satu kota terbesar di Indonesia dan kota terbesar keempat di wilayah Pulau Jawa bagian selatan menurut jumlah penduduk. Kota Yogyakarta juga pernah menjadi ibu kota RI pada tahun 1946.\n" +
                    "\n" +
                    "Salah satu kecamatan di Yogyakarta, yaitu Kotagede pernah menjadi pusat Kesultanan Mataram antara kurun tahun 1575–1640. Keraton (Istana) yang masih berfungsi dalam arti yang sesungguhnya adalah Keraton Ngayogyakarta dan Puro Paku Alaman, yang merupakan pecahan dari Kesultanan Mataram. Pada masa revolusi, Yogyakarta juga pernah menjadi ibu kota Indonesia antara tahun 1946 hingga 1950. \n" +
                    "\n" +
                    "Sebelum Indonesia merdeka, Yogyakarta merupakan daerah yang mempunyai pemerintahan sendiri atau disebut Zelfbestuurlandschappen/Daerah Swapraja, yaitu Kasultanan Ngayogyakarta Hadiningrat dan Kadipaten Pakualaman. Kasultanan Ngayogyakarta Hadiningrat didirikan oleh Pangeran Mangkubumi yang bergelar Sultan Hamengku Buwono I pada tahun 1755, sedangkan Kadipaten Pakualaman didirikan oleh Pangeran Notokusumo (saudara Sultan Hamengku Buwono II) yang bergelar Adipati Paku Alam I pada tahun 1813. Pemerintah Hindia Belanda mengakui Kasultanan, dan Pakualaman sebagai kerajaan dengan hak mengatur rumah tangganya sendiri yang dinyatakan dalam kontrak politik. Kontrak politik yang terakhir Kasultanan tercantum dalam Staatsblaad 1942 Nomor 47, sedangkan kontrak politik Pakualaman dalam Staatsblaad 1941 Nomor 577. Eksistensi kedua kerajaan tersebut telah mendapat pengakuan dari dunia internasional, baik pada masa penjajahan Belanda, Inggris, maupun Jepang. Ketika Jepang meninggalkan Indonesia, kedua kerajaan tersebut telah siap menjadi sebuah negara sendiri yang merdeka, lengkap dengan sistem pemerintahannya (susunan asli), wilayah, dan penduduknya.",

            photo = R.drawable.yogyakarta
        ),
        City(
            id = 5,
            name = "Bandung",
            description = "Kota Bandung adalah kota metropolitan terbesar di Provinsi Jawa Barat, sekaligus menjadi ibu kota provinsi tersebut. Kota ini terletak 140 km sebelah tenggara Jakarta, dan merupakan kota terbesar di wilayah Pulau Jawa bagian barat. Sedangkan wilayah Bandung Raya (Wilayah Metropolitan Bandung) merupakan metropolitan terbesar ketiga di Indonesia setelah Jabodetabek dan Gerbangkertosusila.\n" +
                    "\n" +
                    "Di kota ini tercatat berbagai sejarah penting, di antaranya sebagai tempat berdirinya sebuah perguruan tinggi teknik pertama di Indonesia (Technische Hoogeschool te Bandoeng - TH Bandung, sekarang Institut Teknologi Bandung - ITB), lokasi ajang pertempuran pada masa kemerdekaan, serta pernah menjadi tempat berlangsungnya Konferensi Asia-Afrika 1955, suatu pertemuan yang menyuarakan semangat anti kolonialisme, bahkan Perdana Menteri India Jawaharlal Nehru dalam pidatonya mengatakan bahwa Bandung adalah ibu kotanya Asia-Afrika. Kata Bandung berasal dari kata bendung atau bendungan karena terbendungnya sungai Citarum oleh lava Gunung Tangkuban Parahu yang lalu membentuk telaga. Legenda yang diceritakan oleh orang-orang tua di Bandung mengatakan bahwa nama Bandung diambil dari sebuah kendaraan air yang terdiri dari dua perahu yang diikat berdampingan yang disebut perahu bandung yang digunakan oleh Bupati Bandung, R.A. Wiranatakusumah II, untuk melayari Ci Tarum dalam mencari tempat kedudukan kabupaten yang baru untuk menggantikan ibu kota yang lama di Dayeuhkolot.\n" +
                    "\n" +
                    "Berdasarkan filosofi Sunda, kata Bandung juga berasal dari kalimat Nga-Bandung-an Banda Indung, yang merupakan kalimat sakral dan luhur karena mengandung nilai ajaran Sunda. Nga-Bandung-an artinya menyaksikan atau bersaksi. Banda adalah segala sesuatu yang berada di alam hidup yaitu di bumi dan atmosfer, baik makhluk hidup maupun benda mati. Sinonim dari banda adalah harta. Indung berarti Ibu atau Bumi, disebut juga sebagai Ibu Pertiwi tempat Banda berada.\n" +
                    "\n" +
                    "Dari Bumi-lah semua dilahirkan ke alam hidup sebagai Banda. Segala sesuatu yang berada di alam hidup adalah Banda Indung, yaitu Bumi, air, tanah, api, tumbuhan, hewan, manusia dan segala isi perut bumi. Langit yang berada di luar atmosfer adalah tempat yang menyaksikan, Nu Nga-Bandung-an. Yang disebut sebagai Wasa atau Sang Hyang Wisesa, yang berkuasa di langit tanpa batas dan seluruh alam semesta termasuk Bumi. Jadi kata Bandung mempunyai nilai filosofis sebagai alam tempat segala makhluk hidup maupun benda mati yang lahir dan tinggal di Ibu Pertiwi yang keberadaanya disaksikan oleh yang Maha Kuasa.\n" +
                    "\n" +
                    "Kota Bandung secara geografis memang terlihat dikelilingi oleh pegunungan, dan ini menunjukkan bahwa pada masa lalu kota Bandung memang merupakan sebuah telaga atau danau. Legenda Sangkuriang merupakan legenda yang menceritakan bagaimana terbentuknya danau Bandung, dan bagaimana terbentuknya Gunung Tangkuban Perahu, lalu bagaimana pula keringnya danau Bandung sehingga meninggalkan cekungan seperti sekarang ini. Air dari danau Bandung menurut legenda tersebut kering karena mengalir melalui sebuah gua yang bernama Sanghyang Tikoro.\n" +
                    "\n" +
                    "Daerah terakhir sisa-sisa danau Bandung yang menjadi kering adalah Situ Aksan, yang pada tahun 1970-an masih merupakan danau tempat berpariwisata, tetapi saat ini sudah menjadi daerah perumahan untuk permukiman.\n" +
                    "\n" +
                    "Kota Bandung mulai dijadikan sebagai kawasan permukiman sejak pemerintahan kolonial Hindia Belanda, melalui Gubernur Jenderalnya waktu itu Herman Willem Daendels, mengeluarkan surat keputusan tanggal 25 September 1810 tentang pembangunan sarana dan prasarana untuk kawasan ini. Dikemudian hari peristiwa ini diabadikan sebagai hari jadi kota Bandung.\n" +
                    "\n" +
                    "Kota Bandung secara resmi mendapat status gemeente (kota) dari Gubernur Jenderal J.B. van Heutsz pada tanggal 1 April 1906 dengan luas wilayah waktu itu sekitar 900 ha, dan bertambah menjadi 8.000 ha pada tahun 1949, sampai terakhir bertambah menjadi luas wilayah saat ini.\n" +
                    "\n" +
                    "Pada masa perang kemerdekaan, pada 24 Maret 1946, sebagian kota ini dibakar oleh para pejuang kemerdekaan sebagai bagian dalam strategi perang waktu itu. Peristiwa ini dikenal dengan sebutan Bandung Lautan Api dan diabadikan dalam lagu Halo-Halo Bandung. Selain itu kota ini kemudian ditinggalkan oleh sebagian penduduknya yang mengungsi ke daerah lain.\n" +
                    "\n" +
                    "Pada tanggal 18 April 1955 di Gedung Merdeka yang dahulu bernama Concordia, Jl. Asia Afrika, sekarang, berseberangan dengan Hotel Savoy Homann, diadakan untuk pertama kalinya Konferensi Asia-Afrika yang kemudian kembali KTT Asia-Afrika 2005 diadakan di kota ini pada 19 April-24 April 2005.\n" +
                    "\n" +
                    "Pada tanggal 24 April 2015, Konferensi Asia-Afrika kembali diadakan di kota ini setelah tanggal 20 April-23 April 2015 berlangsung di Jakarta",

            photo = R.drawable.bandung
        ),
        City(
            id = 6,
            name = "Pekanbaru",
            description = "Kota Pekanbaru (Jawi: كوتا ڤكنبارو) adalah ibu kota dan kota terbesar di Provinsi Riau, Indonesia. Kota ini merupakan salah satu sentra ekonomi terbesar di Pulau Sumatra dan termasuk kota dengan tingkat pertumbuhan, migrasi, dan urbanisasi yang tinggi.\n" +
                    "\n" +
                    "Pekanbaru terletak di tepian Sungai Siak dan pada awalnya merupakan sebuah kota kecil yang memiliki pasar (pekan) yang bernama Payung Sekaki atau Senapelan. Pada abad ke-18, wilayah yang kini menjadi Pekanbaru berada pada lingkar pengaruh Kesultanan Siak, dan Sultan Abdul Jalil Alamuddin Syah (\"Marhum Pekan\") secara luas dianggap sebagai pendiri kota Pekanbaru modern; hari jadi kota ini ditetapkan pada tanggal 23 Juni 1784. Pekanbaru menjadi sebuah \"kota kecil\" pada tahun 1948 dan kotapraja pada tahun 1956, sebelum ditetapkan menjadi ibu kota provinsi Riau sebagai pengganti dari Tanjung Pinang pada tahun 1959. Perkembangan kota ini pada awalnya tidak terlepas dari fungsi Sungai Siak sebagai sarana transportasi dalam mendistribusikan hasil bumi dari pedalaman dan dataran tinggi Minangkabau ke wilayah pesisir Selat Malaka. Pada abad ke-18, wilayah Senapelan di tepi Sungai Siak, menjadi pasar (pekan) bagi para pedagang Minangkabau. Seiring dengan berjalannya waktu, daerah ini berkembang menjadi tempat permukiman yang ramai. Sultan Siak ke-4 Sultan Alamuddin Syah memindahkan pusat kekuasaan Siak dari Mempura ke Senapelan pada tahun 1762. Pada tanggal 23 Juni 1784, berdasarkan musyawarah \"Dewan Menteri\" dari Kesultanan Siak, yang terdiri dari datuk empat suku (Pesisir, Limapuluh, Tanah Datar, dan Kampar), kawasan ini dinamai dengan Pekanbaru, dan dikemudian hari diperingati sebagai hari jadi kota ini.\n" +
                    "\n" +
                    "Berdasarkan Besluit van Het Inlandsch Zelfbestuur van Siak No. 1 tanggal 19 Oktober 1919, Pekanbaru menjadi bagian distrik dari Kesultanan Siak. Namun pada tahun 1931, Pekanbaru dimasukkan ke dalam wilayah Kampar Kiri yang dikepalai oleh seorang controleur yang berkedudukan di Pekanbaru dan berstatus landschap sampai tahun 1940. Kemudian menjadi ibu kota Onderafdeling Kampar Kiri sampai tahun 1942. Setelah pendudukan Jepang pada tanggal 8 Maret 1942, Pekanbaru dikepalai oleh seorang gubernur militer yang disebut gokung.[butuh rujukan]\n" +
                    "\n" +
                    "Selepas kemerdekaan Indonesia, berdasarkan Ketetapan Gubernur Sumatra di Medan tanggal 7 Mei 1946 Nomor 103, Pekanbaru dijadikan daerah otonom yang disebut haminte (kotapraja). Kemudian pada tanggal 19 Maret 1956, berdasarkan Undang-undang Nomor 8 Tahun 1956, Pekanbaru (Pakanbaru) menjadi daerah otonom kota kecil dalam lingkungan Provinsi Sumatra Tengah. Selanjutnya sejak tanggal 9 Agustus 1957 berdasarkan Undang-undang Darurat Nomor 19 Tahun 1957, Pekanbaru masuk ke dalam wilayah Provinsi Riau yang baru terbentuk.[14]\n" +
                    "\n" +
                    "Kota Pekanbaru resmi menjadi ibu kota Provinsi Riau pada tanggal 20 Januari 1959 berdasarkan Keputusan Menteri Dalam Negeri Nomor Desember 52/I/44-25. Sebelumnya, ibu kota Riau adalah Tanjung Pinang, yang kini menjadi ibu kota Provinsi Kepulauan Riau.",

            photo = R.drawable.pekanbaru
        ),
        City(
            id = 7,
            name = "Semarang",
            description = "Kota Semarang (bahasa Jawa: ꦏꦸꦛ\u200Bꦯꦼꦩꦫꦁ, translit. Kutha Sêmarang) adalah ibu kota Provinsi Jawa Tengah, Indonesia sekaligus kota metropolitan terbesar kelima di Indonesia setelah Jakarta, Surabaya, Medan, dan Bandung. Sebagai salah satu kota paling berkembang di Pulau Jawa, Kota Semarang mempunyai jumlah penduduk lebih dari 1,7 juta jiwa dan siang hari bisa mencapai 2 juta jiwa. Kawasan mega-urban Semarang yang tergabung dalam wilayah metropolitan Kedungsepur (Kendal, Demak, Ungaran, Kabupaten Semarang, Kota Salatiga, Kota Semarang dan Purwodadi, Kabupaten Grobogan) berpenduduk mencapai 7,3 juta jiwa, sekaligus sebagai wilayah metropolitan terpadat keempat di Pulau Jawa, setelah Jabodetabek (Jakarta), Gerbangkertosusilo (Surabaya), dan Bandung Raya. Dalam beberapa tahun terakhir, perkembangan Semarang yang signifikan ditandai pula dengan munculnya beberapa gedung pencakar langit yang tersebar di penjuru kota. Perkembangan regional ini menunjukan peran strategis Kota Semarang terhadap roda perekonomian nasional. Kota Semarang dipimpin oleh wali kota Hendrar Prihadi, S.E, M.M dan wakil wali kota Ir. Hj. Hevearita Gunaryanti Rahayu. Kota ini terletak sekitar 558 km sebelah timur Jakarta, atau 312 km sebelah barat Surabaya, atau 621 km sebalah barat daya Banjarmasin (via udara).[8] Semarang berbatasan dengan Laut Jawa di sebelah utara, Kabupaten Demak di sebelah timur, Kabupaten Semarang di sebelah selatan, dan Kabupaten Kendal disebelah barat. Kota Semarang memiliki luas wilayah administratif sebesar 373,70 km persegi, sekaligus merupakan administrasi kotamadya terluas di Pulau Jawa.\n" +
                    "\n" +
                    "Secara etimologis, nama \"Semarang\" berasal dari kata \"sem\", yang berarti \"asam/pohon asam\", dan kata \"arang\", yang berarti \"jarang\", yang digabungkan menjadi \"asam yang jarang - jarang\". Penamaan \"Semarang\" ini bermula ketika Ki Ageng Pandanaran I datang ke sebuah pulau bernama Pulau Tirang (dekat pelabuhan Bergota) dan melihat pohon asam yang jarang - jarang tumbuh berdekatan. Penamaan Kota Semarang ini sempat berubah saat zaman kolonialisme Hindia Belanda menjadi \"Samarang\". Kota Semarang merupakan satu dari tiga pusat pelabuhan (Jakarta dan Surabaya) penting bagi Hindia Belanda sebagai pemasok hasil bumi dari wilayah pedalaman Jawa.\n" +
                    "\n" +
                    "Seperti kota - kota besar lainya, Kota Semarang mengenal sistem pembagian wilayah kota yang terdiri atas: Semarang Tengah atau Semarang Pusat, Semarang Timur, Semarang Selatan, Semarang Barat, dan Semarang Utara. Pembagian wilayah kota ini bermula dari pembagian wilayah sub-residen oleh Pemerintah Hindia Belanda yang setingkat dengan kecamatan. Namun saat ini, pembagian wilayah kota ini berbeda dengan pembagian administratif wilayah kecamatan. Meskipun pembagian kota ini jarang dipergunakan dalam lingkungan Pemerintahan Kota Semarang, namun pembagian kota ini digunakan untuk mempermudah dalam menerangkan suatu lokasi menurut letaknya terhadap pusat kota Semarang. Pembagian kota ini juga digunakan oleh beberapa instansi di lingkungan Kota Semarang untuk mempermudah jangkauan pelayanan, seperti PLN dan PDAM. Kota Semarang adalah salah satu kota penting yang terletak di pesisir utara Jawa dan sebagai hub utama penghubung Jakarta - Surabaya dan kota - kota di pedalaman selatan Jawa (Surakarta dan Yogyakarta). Kota Semarang memiliki ketinggian dari 2 meter bawah permukaan laut hingga 340 meter diatas permukaan laut dengan kemiringan lereng 0% - 45%. Kota Semarang merupakan kota yang memiliki kondisi topografi yang unik berupa wilayah dataran rendah yang sempit dan wilayah perbukitan yang memanjang dari sisi barat hingga sisi timur Kota Semarang. Wilayah dataran rendah di Kota Semarang sangat sempit.\n" +
                    "\n" +
                    "Wilayah dataran rendah pada wilayah barat Kota Semarang hanya memiliki lebar 4 kilometer dari garis pantai, sedangkan pada wilayah timur Kota Semarang wilayah dataran rendah semakin melebar hingga 11 kilometer dari garis pantai. Wilayah dataran rendah ini merupakan dataran banjir dari sungai - sungai besar yang mengalir di Kota Semarang, seperti Kali Garang (Banjir Kanal Barat), Kali Pengkol, dan Kali Bringin. Wilayah dataran rendah ini membentang di sisi utara Kota Semarang dan hampir mencakup 40% total wilayah Kota Semarang. Wilayah dataran rendah ini dikenal sebagai kota bawah (Semarang Ngisor), sekaligus sebagai pusat aktivitas perekonomian kota. Dengan kondisi demikian, wilayah kota bawah sering kali dilanda banjir tahunan dan puncaknya ketika musim penghujan. Sejumlah wilayah khususnya Semarang Utara, banjir ini kadang juga disebabkan luapan air pasang laut (banjir rob). Wilayah perbukitan di Kota Semarang ini membentang di sisi selatan. Perbukitan ini merupakan bagian dari rangkaian formasi pegunungan utara Jawa yang membentang dari Banten hingga Jawa Timur. Wilayah perbukitan di Kota Semarang dikenal sebagai kota atas (Semarang Dhuwur). Wilayah perbukitan ini juga merupakan kawasan hulu dari sungai - sungai besar yang mengalir di Kota Semarang. Wilayah kota atas juga bagian dari bentang kaki gunung api Ungaran, yang terletak pada sisi selatan Kota Semarang.",

            photo = R.drawable.jakarta
        ),
        City(
            id = 8,
            name = "Surabaya",
            description = "Kota Surabaya (Hanacaraka: ꦑꦸꦛꦯꦸꦫꦧꦪ; Pegon Jawa: كوڟاسورابايا, tr. Kutha Surabaya, pengucapan bahasa Jawa: [kuʈɔ surɔˈbɔjɔ]. Pegon Madura: سَوربٓجٓه, tr. Sorbhâjâh. Hanzi: 泗水) adalah ibu kota Provinsi Jawa Timur, Indonesia, sekaligus kota metropolitan terbesar di provinsi tersebut. Surabaya merupakan kota terbesar kedua di Indonesia setelah Jakarta. Kota ini terletak 800 km sebelah timur Jakarta, atau 435 km sebelah barat laut Denpasar, Bali. Surabaya terletak di pantai utara Pulau Jawa bagian timur dan berhadapan dengan Selat Madura serta Laut Jawa.\n" +
                    "\n" +
                    "Surabaya memiliki luas sekitar ±326,81 km², dan 3.158.943 jiwa penduduk pada tahun 2019. Daerah metropolitan Surabaya yaitu Gerbangkertosusila yang berpenduduk sekitar 10 juta jiwa, adalah kawasan metropolitan terbesar kedua di Indonesia setelah Jabodetabek. Surabaya dan wilayah Gerbangkertosusila dilayani oleh sebuah bandar udara, yakni Bandar Udara Internasional Juanda yang berada 20 km di sebelah selatan kota, serta dua pelabuhan, yakni Pelabuhan Tanjung Perak dan Pelabuhan Ujung. Wilayah Surabaya dahulu merupakan gerbang utama untuk memasuki ibu kota Kerajaan Majapahit dari arah lautan, yakni di muara Kali Mas. Bahkan hari jadi kota Surabaya ditetapkan yaitu pada tanggal 31 Mei 1293. Hari itu sebenarnya merupakan hari kemenangan pasukan Majapahit yang dipimpin Raden Wijaya terhadap serangan pasukan Mongol. Pasukan Mongol yang datang dari laut digambarkan sebagai SURA (ikan hiu / berani) dan pasukan Raden Wijaya yang datang dari darat digambarkan sebagai BAYA (buaya / bahaya), jadi secara harfiah diartikan berani menghadapi bahaya yang datang mengancam. Maka hari kemenangan itu diperingati sebagai hari jadi Surabaya.\n" +
                    "\n" +
                    "Pada abad ke-15, Islam mulai menyebar dengan pesat di daerah Surabaya. Salah satu anggota Walisongo, Sunan Ampel, mendirikan masjid dan pesantren di wilayah Ampel. Tahun 1530, Surabaya menjadi bagian dari Kerajaan Demak.\n" +
                    "\n" +
                    "Menyusul runtuhnya Demak, Surabaya menjadi sasaran penaklukan Kesultanan Mataram, diserbu Panembahan Senopati tahun 1598, diserang besar-besaran oleh Panembahan Seda ing Krapyak tahun 1610, dan diserang Sultan Agung tahun 1614. Pemblokan aliran Sungai Brantas oleh Sultan Agung akhirnya memaksa Surabaya menyerah. Suatu tulisan VOC tahun 1620 menggambarkan, Surabaya sebagai wilayah yang kaya dan berkuasa. Panjang lingkarannya sekitar 5 mijlen Belanda (sekitar 37 km), dikelilingi kanal dan diperkuat meriam. Tahun tersebut, untuk melawan Mataram, tentaranya sebesar 30.000 prajurit[8].\n" +
                    "\n" +
                    "Tahun 1675, Trunojoyo dari Madura merebut Surabaya, namun akhirnya didepak VOC pada tahun 1677.\n" +
                    "\n" +
                    "Dalam perjanjian antara Pakubuwono II dan VOC pada tanggal 11 November 1743, Surabaya diserahkan penguasaannya kepada VOC. Gedung pusat pemerintahan Karesidenan Surabaya berada di mulut sebelah barat Jembatan Merah. Jembatan inilah yang membatasi permukiman orang Eropa (Europeesche Wijk) waktu itu, yang ada di sebelah barat jembatan dengan tempat permukiman orang Tionghoa; Melayu; Arab; dan sebagainya (Vremde Oosterlingen), yang ada di sebelah timur jembatan tersebut. Hingga tahun 1900-an, pusat kota Surabaya hanya berkisar di sekitar Jembatan Merah saja.",
            photo = R.drawable.surabaya
        ),
        City(
            id = 9,
            name = "Jayapura",
            description = "Kota Jayapura adalah ibu kota provinsi Papua, Indonesia. Kota ini merupakan ibu kota provinsi yang terletak paling timur di Indonesia. Kota ini terletak di teluk Jayapura. Kota ini didirikan oleh Kapten Infanteri F.J.P Sachse dari kerajaan Belanda pada 7 Maret 1910. Dari tahun 1910 ke 1962, kota ini dikenal sebagai Hollandia dan merupakan ibu kota distrik dengan nama yang sama di timur laut pulau Papua bagian barat. Kota ini sempat disebut Kota Baru dan Sukarnopura (Sukarnapura, 1964) sebelum menyandang nama yang sekarang pada tahun 1968. Arti literal dari Jayapura, sebagaimana kota Jaipur di Rajasthan, adalah 'Kota Kemenangan' (bahasa Sanskerta: jaya yang berarti \"kemenangan\"; pura: \"kota\"). Kota Jayapura telah sejak lama bersentuhan dengan dunia luar. Hal ini ditunjukkan dengan adanya orang-orang yang pernah singgah di Tanah Papua seperti seseorang berbangsa Spanyol bernama Ynico Ortis de Fretes. Dengan kapalnya yang bernama \"San Juan\", Ynico berlayar pada tanggal 16 Mei 1545 dari Tidore ke Meksiko. Dalam perjalanan tersebut, rombongan Ynico tiba di sekitar muara sungai Mamberamo pada tanggal 16 Juni 1545 memberikan nama \"Nova Guinea\" kepada tanah Papua.\n" +
                    "\n" +
                    "Sesudah Ortis de Fretes, muncul lagi pengarung-pengarung lain antara lain Alvaro Memdana Ne Neyra (1567) dan Antonio Ma (1591-1593)\n" +
                    "\n" +
                    "Selanjutnya Besleit (Surat Keputusan) Gubernemen Hindia Belanda Nomor 4 tanggal 28 Agustus 1909 kepada Asisten residen, di Manokwari diperbantukan 1 detasemen (4 Perwira + 80 tentara). Dalam surat keputusan tersebut antara lain tertera (dalam bahasa Belanda) diterjemahkan kedalam Bahasa Indonesia.\n" +
                    "\n" +
                    "Sebagai lanjutan dari pelaksanaan surat keputusan ini, maka pada tanggal 28 September 1909 kapal \"EDI\" mendaratkan satu detasemen tentara di bawah komando Kapten Infanteri F.J.P SACHSE, segera dimulai menebang pohon-pohon, tetapi segera pula pembayaran ganti rugi harus dilakukan kepada pemiliknya seharga 40 ringgit atau 40 * f 2,50 = f 100,- (seratus gulden / rupiah). Suatu jumlah yang sangat besar waktu itu - 1910 seorang ahli lain bernama KIELICH menulis \"Hollandia kostte vierting (40) rijk dealders\" Jayapura harganya 40 ringgit f 100,- (seratus golden/rupiah). Bedilh kmpamen pertama yang terdiri dari tenda-tenda, tetapi segera diusahakan untuk mendirikan perumahan-perumahan dari bahan sekitar tempat itu.\n" +
                    "\n" +
                    "Penghuni-penghuni pertama terdiri dari 4 Perwira, 80 anggota tentara, 60 pemikul, beberapa pembantu dan istri-istri para angkatan bersenjata ini, total keseluruhan berjumlah 290 orang.\n" +
                    "\n" +
                    "Ada 2 sungai masing-masing Numbai dan Anafri yang menyatu dan bermuara di teluk Numbai atau Yos Sudarso, dengan sebutan populer muara sungai Numbai. Sungai Numbai-Anafri mengalir satu ngarai yang berawa-rawa penuh dengan pohon-pohon sagu dan bermata air di pegunungan Cyclop.",
            photo = R.drawable.jayapura
        ),
        City(
            id = 10,
            name = "Medan",
            description = "Kota Medan (Jawi: ميدن; Batak: ᯔᯩᯑᯉ᯲; Pegon: مَيدان; Hanzi: 棉蘭; Tamil: மேடான்) adalah ibu kota provinsi Sumatra Utara, Indonesia. Kota ini merupakan kota terbesar ketiga di Indonesia setelah DKI Jakarta dan Surabaya, serta kota terbesar di luar pulau Jawa. Kota Medan merupakan pintu gerbang wilayah Indonesia bagian barat dengan keberadaan Pelabuhan Belawan dan Bandar Udara Internasional Kuala Namu yang merupakan bandara terbesar kedua di Indonesia. Akses dari pusat kota menuju pelabuhan dan bandara dilengkapi oleh jalan tol dan kereta api. Medan adalah kota pertama di Indonesia yang mengintegrasikan bandara dengan kereta api. Berbatasan dengan Selat Malaka, Medan menjadi kota perdagangan, industri, dan bisnis yang sangat penting di Indonesia. Pada tahun 2020, kota Medan memiliki penduduk sebanyak 2.524.321 jiwa, dan kepadatan penduduk 9.522,22 jiwa/km2. Medan berasal dari kata bahasa Tamil Maidhan atau Maidhanam, yang berarti tanah lapang atau tempat yang luas, yang kemudian teradopsi ke Bahasa Melayu.\n" +
                    "\n" +
                    "Hari jadi Kota Medan diperingati tiap tahun sejak tahun 1970 yang pada mulanya ditetapkan pada tanggal 1 April 1909. Tanggal ini kemudian mendapat bantahan yang cukup keras dari kalangan pers dan beberapa ahli sejarah. Karena itu, Wali kota membentuk panitia sejarah hari jadi Kota Medan untuk melakukan penelitian dan penyelidikan. Surat Keputusan Wali kotamadya Kepala Daerah Kotamadya Medan No. 342 tanggal 25 Mei 1971 yang waktu itu dijabat oleh Drs. Sjoerkani membentuk Panitia Peneliti Hari Jadi Kota Medan. Duduk sebagai Ketua adalah Prof. Mahadi, SH, Sekretaris Syahruddin Siwan, MA, Anggotanya antara lain Ny. Mariam Darus, SH dan T.Luckman, SH. Untuk lebih mengintensifkan kegiatan kepanitiaan ini dikeluarkan lagi Surat Keputusan Wali kotamadya Kepala Daerah Kotamadya Medan No.618 tanggal 28 Oktober 1971 tentang Pembentukan Panitia Penyusun Sejarah Kota Medan dengan Ketuanya Prof.Mahadi, SH, Sekretaris Syahruddin Siwan, MA dan Anggotanya H. Mohammad Said, Dada Meuraxa, Letkol. Nas Sebayang, Nasir Tim Sutannaga, M.Solly Lubis, SH, Drs. Payung Bangun, MA dan R. Muslim Akbar. DPRD Medan sepenuhnya mendukung kegiatan kepanitiaan ini sehingga merekapun membentuk Pansus dengan ketua M.A. Harahap, beranggotakan antara lain Drs. M.Hasan Ginting, Ny. Djanius Djamin SH., Badar Kamil, BA dan Mas Sutarjo.\n" +
                    "\n" +
                    "Dalam buku The History of Medan tulisan Tengku Luckman Sinar (1991), dituliskan bahwa menurut \"Hikayat Aceh\", Medan sebagai pelabuhan telah ada pada tahun 1590, dan sempat dihancurkan selama serangan Sultan Aceh Alauddin Saidi Mukammil kepada Raja Haru yang berkuasa di situ. Serangan serupa dilakukan Sultan Iskandar Muda tahun 1613, terhadap Kesultanan Deli. Sejak akhir abad ke-16, nama Haru berubah menjadi Ghuri, dan akhirnya pada awal abad ke-17 menjadi Deli. Pertempuran terus-menerus antara Haru dengan Aceh mengakibatkan penduduk Haru jauh berkurang. Sebagai daerah taklukan, banyak warganya yang dipindahkan ke Aceh untuk dijadikan pekerja kasar.\n" +
                    "\n" +
                    "Selain dengan Aceh, Kerajaan Haru yang makmur ini juga tercatat sering terlibat pertempuran dengan Kerajaan Melayu di Semenanjung Malaka dan juga dengan kerajaan dari Jawa. Serangan dari Pulau Jawa ini antara lain tercatat dalam kitab Pararaton yang dikenal dengan Ekspedisi Pamalayu. Dalam Negarakertagama, Mpu Prapanca juga menuliskan bahwa selain Pane (Panai), Majapahit juga menaklukkan Kampe (Kampai) dan Harw (Haru). Berkurangnya penduduk daerah pantai timur Sumatra akibat berbagai perang ini, lalu diikuti dengan mulai mengalirnya suku-suku dari dataran tinggi pedalaman turun ke pesisir pantai timur Sumatra. Suku Karo bermigrasi ke daerah pantai Langkat, Serdang, dan Deli. Suku Simalungun ke daerah pantai Batubara dan Asahan, serta suku Mandailing ke daerah pantai Kualuh, Kota Pinang, Panai, dan Bilah.",
            photo = R.drawable.medan
        ),
        City(
            id = 11,
            name = "Batam",
            description = "Kota Batam adalah kota terbesar di Provinsi Kepulauan Riau, Indonesia. Wilayah Kota Batam terdiri dari Pulau Batam, Pulau Rempang dan Pulau Galang dan pulau-pulau kecil lainnya di kawasan Selat Singapura dan Selat Malaka. Pulau Batam, Rempang, dan Galang terkoneksi oleh Jembatan Barelang. Menurut Dinas Kependudukan dan Catatan Sipil Kota Batam, pada tahun 2020 jumlah penduduk Batam mencapai 1.157.882 jiwa, dengan kepadatan 1.206,13 jiwa/km². Kota Batam merupakan bagian dari kawasan khusus perdagangan bebas Batam–Bintan–Karimun (BBK).\n" +
                    "\n" +
                    "Batam merupakan salah satu kota dengan letak yang sangat strategis. Selain berada di jalur pelayaran internasional, kota ini memiliki jarak yang sangat dekat dan berbatasan langsung dengan Singapura dan Malaysia. Sebagai kota terencana, Batam merupakan salah satu kota dengan pertumbuhan terpesat di Indonesia. Ketika dibangun pada tahun 1970-an oleh Otorita Batam (saat ini bernama BP Batam), kota ini hanya dihuni sekitar 6.000 penduduk dan dalam tempo 40 tahun penduduk Batam bertumbuh hingga 158 kali lipat. Pulau Batam dihuni pertama kali oleh orang Melayu dengan sebutan orang selat sejak tahun 231 Masehi. Pulau yang pernah menjadi medan perjuangan Laksamana Hang Nadim dalam melawan penjajah ini digunakan oleh pemerintah pada dekade 1960-an sebagai basis logistik minyak bumi di Pulau Sambu.\n" +
                    "\n" +
                    "Pada dekade 1970-an, dengan tujuan awal menjadikan Batam sebagai Singapura-nya Indonesia, maka sesuai Keputusan Presiden nomor 41 tahun 1973, Pulau Batam ditetapkan sebagai lingkungan kerja daerah industri dengan didukung oleh Otorita Pengembangan Daerah Industri Pulau Batam atau lebih dikenal dengan Badan Otorita Batam (BOB) sebagai penggerak pembangunan Batam. Kini menjadi Badan Pengusahaan (BP Batam).Seiring pesatnya perkembangan Pulau Batam, pada dekade 1980-an, berdasarkan Peraturan Pemerintah Nomor 34 tahun 1983, wilayah Kecamatan Batam yang merupakan bagian dari Kabupaten Kepulauan Riau, ditingkatkan statusnya menjadi Kotamadya Batam yang memiliki tugas dalam menjalankan administrasi pemerintahan dan kemasyarakatan serta mendudukung pembangunan yang dilakukan Otorita Batam (BP Batam).\n" +
                    "\n" +
                    "Di era reformasi pada akhir dekade tahun 1990-an, dengan Undang-Undang nomor 53 tahun 1999, maka Kotamadya administratif Batam berubah statusnya menjadi daerah otonomi, yaitu Pemerintah Kota Batam untuk menjalankan fungsi pemerintahan dan pembangunan dengan mengikutsertakan Badan Otorita Batam (BP Batam).",
            photo = R.drawable.batam
        ),

        )
}